version: "3.9"
services:
    mariadb:
      build: requirements/mariadb
      container_name: mariadb
      image: mariadb
      networks:
        - network
      ports:
        - "3306:3306"
      volumes:
        - "database:/var/lib/mysql"
      restart: unless-stopped
    wordpress:
      build: requirements/wordpress
      container_name: wordpress
      image: wordpress
      networks:
        - network
      ports:
        - "9000:9000"
      depends_on:
        - mariadb
      volumes:
        - "www:/var/www/html/"
      restart: unless-stopped
    nginx:
      build: requirements/nginx
      container_name: nginx
      image: nginx
      networks:
        - network
      ports:
        - "443:443"
      depends_on:
        - mariadb
      volumes:
        - "www:/var/www/html/"
      restart: unless-stopped
volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: /home/rrollin/data/www
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/rrollin/data/database
      o: bind
networks:
  network:
